import type { User, Match, Bet } from '../types';

const now = new Date();

export const mockUsers: User[] = [
  {
    id: 'user1',
    nickname: '大力水手',
    avatar: '⚽️',
    isAdmin: true,
    createdAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user2',
    nickname: '球王梅西',
    avatar: '🐐',
    isAdmin: false,
    createdAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user3',
    nickname: 'C罗铁粉',
    avatar: '👑',
    isAdmin: false,
    createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user4',
    nickname: '内马尔滚',
    avatar: '🤸',
    isAdmin: false,
    createdAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user5',
    nickname: '姆巴佩冲',
    avatar: '🚀',
    isAdmin: false,
    createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user6',
    nickname: '魔笛悠扬',
    avatar: '🎵',
    isAdmin: false,
    createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user7',
    nickname: '德布劳内传',
    avatar: '🎯',
    isAdmin: false,
    createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'user8',
    nickname: '哈兰德冲',
    avatar: '😈',
    isAdmin: false,
    createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

const baseDate = new Date('2026-06-10T18:00:00');

export const mockMatches: Match[] = [
  {
    id: 'match1',
    homeTeam: '阿根廷',
    awayTeam: '巴西',
    homeFlag: '🇦🇷',
    awayFlag: '🇧🇷',
    matchTime: new Date(baseDate.getTime() + 0 * 24 * 60 * 60 * 1000).toISOString(),
    stage: 'group',
    groupName: 'A',
    homeScore: 2,
    awayScore: 1,
    status: 'finished',
  },
  {
    id: 'match2',
    homeTeam: '法国',
    awayTeam: '德国',
    homeFlag: '🇫🇷',
    awayFlag: '🇩🇪',
    matchTime: new Date(baseDate.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    stage: 'group',
    groupName: 'B',
    homeScore: 1,
    awayScore: 1,
    status: 'finished',
  },
  {
    id: 'match3',
    homeTeam: '英格兰',
    awayTeam: '西班牙',
    homeFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    awayFlag: '🇪🇸',
    matchTime: new Date(baseDate.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    stage: 'group',
    groupName: 'C',
    homeScore: 0,
    awayScore: 2,
    status: 'finished',
  },
  {
    id: 'match4',
    homeTeam: '葡萄牙',
    awayTeam: '荷兰',
    homeFlag: '🇵🇹',
    awayFlag: '🇳🇱',
    matchTime: new Date(baseDate.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    stage: 'group',
    groupName: 'D',
    homeScore: 3,
    awayScore: 2,
    status: 'finished',
  },
  {
    id: 'match5',
    homeTeam: '比利时',
    awayTeam: '意大利',
    homeFlag: '🇧🇪',
    awayFlag: '🇮🇹',
    matchTime: new Date(baseDate.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    stage: 'group',
    groupName: 'E',
    homeScore: 1,
    awayScore: 0,
    status: 'finished',
  },
  {
    id: 'match6',
    homeTeam: '克罗地亚',
    awayTeam: '摩洛哥',
    homeFlag: '🇭🇷',
    awayFlag: '🇲🇦',
    matchTime: new Date(baseDate.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    stage: 'group',
    groupName: 'F',
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
  },
  {
    id: 'match7',
    homeTeam: '乌拉圭',
    awayTeam: '哥伦比亚',
    homeFlag: '🇺🇾',
    awayFlag: '🇨🇴',
    matchTime: new Date(baseDate.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    stage: 'group',
    groupName: 'G',
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
  },
  {
    id: 'match8',
    homeTeam: '日本',
    awayTeam: '韩国',
    homeFlag: '🇯🇵',
    awayFlag: '🇰🇷',
    matchTime: new Date(baseDate.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    stage: 'group',
    groupName: 'H',
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
  },
];

const formatDate = (daysOffset: number): string => {
  const d = new Date(baseDate.getTime() + daysOffset * 24 * 60 * 60 * 1000);
  return d.toISOString().split('T')[0];
};

export const mockBets: Bet[] = [
  {
    id: 'bet1',
    userId: 'user1',
    date: formatDate(-2),
    amount: 200,
    profitLoss: 220,
    note: '买了3场，中了2场',
    createdAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet2',
    userId: 'user2',
    date: formatDate(-2),
    amount: 500,
    profitLoss: 550,
    note: '重注阿根廷赢',
    createdAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet3',
    userId: 'user3',
    date: formatDate(-2),
    amount: 300,
    profitLoss: -300,
    note: '冷门没防住',
    createdAt: new Date(baseDate.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet4',
    userId: 'user4',
    date: formatDate(-1),
    amount: 100,
    profitLoss: 250,
    note: '2串1中了',
    createdAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet5',
    userId: 'user5',
    date: formatDate(-1),
    amount: 200,
    profitLoss: -200,
    note: '全黑',
    createdAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet6',
    userId: 'user1',
    date: formatDate(-1),
    amount: 150,
    profitLoss: -150,
    note: '小注试试水',
    createdAt: new Date(baseDate.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet7',
    userId: 'user2',
    date: formatDate(0),
    amount: 400,
    profitLoss: 720,
    note: '3串1命中',
    createdAt: new Date(baseDate.getTime()).toISOString(),
  },
  {
    id: 'bet8',
    userId: 'user6',
    date: formatDate(0),
    amount: 200,
    profitLoss: -200,
    note: '',
    createdAt: new Date(baseDate.getTime()).toISOString(),
  },
  {
    id: 'bet9',
    userId: 'user3',
    date: formatDate(1),
    amount: 600,
    profitLoss: 480,
    note: '平局高赔收米',
    createdAt: new Date(baseDate.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet10',
    userId: 'user7',
    date: formatDate(1),
    amount: 250,
    profitLoss: -250,
    note: '',
    createdAt: new Date(baseDate.getTime() + 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet11',
    userId: 'user8',
    date: formatDate(2),
    amount: 350,
    profitLoss: 455,
    note: '',
    createdAt: new Date(baseDate.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet12',
    userId: 'user5',
    date: formatDate(2),
    amount: 200,
    profitLoss: -200,
    note: '让球黑了',
    createdAt: new Date(baseDate.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet13',
    userId: 'user1',
    date: formatDate(3),
    amount: 300,
    profitLoss: 180,
    note: '',
    createdAt: new Date(baseDate.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet14',
    userId: 'user2',
    date: formatDate(3),
    amount: 200,
    profitLoss: -200,
    note: '',
    createdAt: new Date(baseDate.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet15',
    userId: 'user4',
    date: formatDate(4),
    amount: 150,
    profitLoss: 210,
    note: '',
    createdAt: new Date(baseDate.getTime() + 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet16',
    userId: 'user6',
    date: formatDate(5),
    amount: 250,
    profitLoss: -250,
    note: '',
    createdAt: new Date(baseDate.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet17',
    userId: 'user1',
    date: formatDate(6),
    amount: 100,
    profitLoss: 635,
    note: '6串1大奶！',
    createdAt: new Date(baseDate.getTime() + 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bet18',
    userId: 'user3',
    date: formatDate(7),
    amount: 200,
    profitLoss: 3098,
    note: '8串1全中！！',
    createdAt: new Date(baseDate.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
